/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BirthdayCake: typeof import('./src/components/BirthdayCake.vue')['default']
    Components: typeof import('./src/components/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    LikeBtn: typeof import('./src/components/LikeBtn.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
  }
}
